Revert "向bochs添加libfmt失败：libfmt修改例子 编译报错 (错误undefined reference to fmt...)"
This reverts commit 6095bdc3810105ed6ffd15c9bc185a87ec115e53.