percpu.h应用patch 后导致之前没出现过的错误：mm/vmstat.c:322:1: error: unsupported size for integer register
percpu.h应用的patch如下:
https://github.com/ClangBuiltLinux/linux/issues/194#issuecomment-548710288
https://lore.kernel.org/all/CAK8P3a1EBaWdbAEzirFDSgHVJMtWjuNt2HGG8z+vpXeNHwETFQ@mail.gmail.com/



percpu.h应用的patch后导致之前没出现过的错误：mm/vmstat.c:322:1: error: unsupported size for integer register
i686-linux-gnu-gcc -Wp,-MD,mm/.vmstat.o.d -nostdinc -isystem /usr/lib/gcc-cross/i686-linux-gnu/11/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-address-of-packed-member -Wno-attribute-alias -O2 -fno-allow-store-data-races -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=./= -Wno-packed-not-aligned    -DKBUILD_BASENAME='"vmstat"'  -DKBUILD_MODNAME='"vmstat"' -c -o mm/vmstat.o mm/vmstat.c
mm/vmstat.c:1:9: note: ‘#pragma message: funcId_asm_inserted’
    1 | #pragma message("funcId_asm_inserted")
      |         ^~~~~~~
mm/vmstat.c: In function ‘sum_vm_events’:
mm/vmstat.c:42:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   42 |         int cpu;
      |         ^~~
mm/vmstat.c: In function ‘vm_events_fold_cpu’:
mm/vmstat.c:76:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   76 |         struct vm_event_state *fold_state = &per_cpu(vm_event_states, cpu);
      |         ^~~~~~
mm/vmstat.c: In function ‘calculate_pressure_threshold’:
mm/vmstat.c:103:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  103 |         int threshold;
      |         ^~~
mm/vmstat.c: In function ‘calculate_normal_threshold’:
mm/vmstat.c:127:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  127 |         int threshold;
      |         ^~~
mm/vmstat.c: In function ‘refresh_zone_stat_thresholds’:
mm/vmstat.c:177:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  177 |         struct pglist_data *pgdat;
      |         ^~~~~~
mm/vmstat.c: In function ‘set_pgdat_percpu_threshold’:
mm/vmstat.c:223:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  223 |         struct zone *zone;
      |         ^~~~~~
mm/vmstat.c: In function ‘__mod_zone_page_state’:
mm/vmstat.c:248:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  248 |         struct per_cpu_pageset __percpu *pcp = zone->pageset;
      |         ^~~~~~
mm/vmstat.c: In function ‘__mod_node_page_state’:
mm/vmstat.c:268:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  268 |         struct per_cpu_nodestat __percpu *pcp = pgdat->per_cpu_nodestats;
      |         ^~~~~~
mm/vmstat.c: In function ‘__inc_zone_state’:
mm/vmstat.c:310:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  310 |         struct per_cpu_pageset __percpu *pcp = zone->pageset;
      |         ^~~~~~
mm/vmstat.c: In function ‘__inc_node_state’:
mm/vmstat.c:326:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  326 |         struct per_cpu_nodestat __percpu *pcp = pgdat->per_cpu_nodestats;
      |         ^~~~~~
mm/vmstat.c: In function ‘__dec_zone_state’:
mm/vmstat.c:354:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  354 |         struct per_cpu_pageset __percpu *pcp = zone->pageset;
      |         ^~~~~~
mm/vmstat.c: In function ‘__dec_node_state’:
mm/vmstat.c:370:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  370 |         struct per_cpu_nodestat __percpu *pcp = pgdat->per_cpu_nodestats;
      |         ^~~~~~
mm/vmstat.c: In function ‘mod_zone_state’:
mm/vmstat.c:412:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  412 |         struct per_cpu_pageset __percpu *pcp = zone->pageset;
      |         ^~~~~~
mm/vmstat.c: In function ‘mod_node_state’:
mm/vmstat.c:469:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  469 |         struct per_cpu_nodestat __percpu *pcp = pgdat->per_cpu_nodestats;
      |         ^~~~~~
mm/vmstat.c: In function ‘fold_diff’:
mm/vmstat.c:640:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  640 |         int i;
      |         ^~~
mm/vmstat.c: In function ‘refresh_cpu_vm_stats’:
mm/vmstat.c:676:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  676 |         struct pglist_data *pgdat;
      |         ^~~~~~
mm/vmstat.c: In function ‘cpu_vm_stats_fold’:
mm/vmstat.c:778:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  778 |         struct pglist_data *pgdat;
      |         ^~~~~~
mm/vmstat.c: In function ‘drain_zonestat’:
mm/vmstat.c:844:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  844 |         int i;
      |         ^~~
mm/vmstat.c: In function ‘fill_contig_page_info’:
mm/vmstat.c:953:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  953 |         unsigned int order;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘__fragmentation_index’:
mm/vmstat.c:985:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  985 |         unsigned long requested = 1UL << order;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘fragmentation_index’:
mm/vmstat.c:1009:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1009 |         struct contig_page_info info;
      |         ^~~~~~
mm/vmstat.c: In function ‘frag_start’:
mm/vmstat.c:1227:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1227 |         pg_data_t *pgdat;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘frag_next’:
mm/vmstat.c:1240:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1240 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘walk_zones_in_node’:
mm/vmstat.c:1258:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1258 |         struct zone *zone;
      |         ^~~~~~
mm/vmstat.c: In function ‘frag_show_print’:
mm/vmstat.c:1279:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1279 |         int order;
      |         ^~~
mm/vmstat.c: In function ‘frag_show’:
mm/vmstat.c:1292:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1292 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘pagetypeinfo_showfree_print’:
mm/vmstat.c:1300:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1300 |         int order, mtype;
      |         ^~~
mm/vmstat.c: In function ‘pagetypeinfo_showfree’:
mm/vmstat.c:1328:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1328 |         int order;
      |         ^~~
mm/vmstat.c: In function ‘pagetypeinfo_showblockcount_print’:
mm/vmstat.c:1345:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1345 |         int mtype;
      |         ^~~
mm/vmstat.c: In function ‘pagetypeinfo_showblockcount’:
mm/vmstat.c:1381:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1381 |         int mtype;
      |         ^~~
mm/vmstat.c: In function ‘pagetypeinfo_show’:
mm/vmstat.c:1426:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1426 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘is_zone_first_populated’:
mm/vmstat.c:1482:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1482 |         int zid;
      |         ^~~
mm/vmstat.c: In function ‘zoneinfo_show_print’:
mm/vmstat.c:1497:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1497 |         int i;
      |         ^~~
mm/vmstat.c: In function ‘zoneinfo_show’:
mm/vmstat.c:1589:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1589 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘vmstat_start’:
mm/vmstat.c:1622:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1622 |         unsigned long *v;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘vmstat_show’:
mm/vmstat.c:1676:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1676 |         unsigned long *l = arg;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘vmstat_refresh’:
mm/vmstat.c:1728:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1728 |         long val;
      |         ^~~~
mm/vmstat.c: In function ‘need_update’:
mm/vmstat.c:1800:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1800 |         struct zone *zone;
      |         ^~~~~~
mm/vmstat.c: In function ‘vmstat_shepherd’:
mm/vmstat.c:1862:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1862 |         int cpu;
      |         ^~~
mm/vmstat.c: In function ‘start_shepherd_timer’:
mm/vmstat.c:1880:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1880 |         int cpu;
      |         ^~~
mm/vmstat.c: In function ‘init_cpu_node_state’:
mm/vmstat.c:1892:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1892 |         int node;
      |         ^~~
mm/vmstat.c: In function ‘vmstat_cpu_dead’:
mm/vmstat.c:1915:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1915 |         const struct cpumask *node_cpus;
      |         ^~~~~
mm/vmstat.c: In function ‘init_mm_internals’:
mm/vmstat.c:1935:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1935 |         int ret __maybe_unused;
      |         ^~~
mm/vmstat.c: In function ‘unusable_show_print’:
mm/vmstat.c:1992:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1992 |         unsigned int order;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘unusable_show’:
mm/vmstat.c:2019:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 2019 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘extfrag_show_print’:
mm/vmstat.c:2052:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 2052 |         unsigned int order;
      |         ^~~~~~~~
mm/vmstat.c: In function ‘extfrag_show’:
mm/vmstat.c:2075:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 2075 |         pg_data_t *pgdat = (pg_data_t *)arg;
      |         ^~~~~~~~~
mm/vmstat.c: In function ‘extfrag_debug_init’:
mm/vmstat.c:2103:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 2103 |         struct dentry *extfrag_debug_root;
      |         ^~~~~~
mm/vmstat.c: In function ‘__inc_zone_state’:
mm/vmstat.c:322:1: error: unsupported size for integer register
  322 | }
      | ^
mm/vmstat.c: Assembler messages:
mm/vmstat.c:315: Error: bad register name `%sil'
make[1]: *** [scripts/Makefile.build:330: mm/vmstat.o] Error 1
make: *** [Makefile:1068: mm] Error 2